apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: default
spec:
  selector:
    app: goapp
  type: NodePort
  ports:
  - name: go-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30007