# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go_ingress
  namespace: default
spec:
  rules:
  - host: go.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go_service
            port:
              number: 8080